cluster:
	eksctl create cluster --name k8sCluster1 --version 1.23 --region us-east-1 --nodegroup-name linux-node --node-type t3.medium --nodes 1

clear:
	eksctl delete cluster --name k8sCluster --region us-east-1 --wait